apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: metadata
  labels:
    app: guestbook
    tier: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      tier: backend
  template:
    metadata:
      labels:
        tier: backend
    spec:
      containers:
        - name: metadata
          image: luckyganesh/metadata-service:v2
          env:
            - name: MONGODB_URI
              value: mongodb://mongo/metadata
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
