kind: PersistentVolume
apiVersion: v1
metadata:
  name: hostpath-pv
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  storageClassName: standard
  hostPath:
    path: "/tmp/data1"
