apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: mongo
  name: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mongo
    spec:
      containers:
      - image: mongo
        name: mongo
        resources: {}
        volumeMounts:
          - name: mongo-persistance
            mountPath: /data/db
      volumes:
        - name: mongo-persistance
          hostPath: 
            type: DirectoryOrCreate
            path: /tmp/mani
status: {}
